import type { Puzzle } from "./types";

export const PUZZLES: Puzzle[] = [
  {
    id: "easy-001",
    title: "1手で勝て",
    difficulty: "easy",
    player: { left: 1, right: 3 },
    cpu: { left: 0, right: 4 },
    mateIn: 1,
    solution: { type: "attack", from: "left", target: "right" },
    hint: "4の手は、1を足すと5になります。",
    explanation: "左手(1)でCPUの右手(4)を攻撃。1 + 4 = 5 なのでDOWN、CPUは両手DOWNです。",
  },
  {
    id: "easy-002",
    title: "最後の2を倒せ",
    difficulty: "easy",
    player: { left: 3, right: 1 },
    cpu: { left: 2, right: 0 },
    mateIn: 1,
    solution: { type: "attack", from: "left", target: "left" },
    hint: "2に3を足すと5です。",
    explanation: "左手(3)でCPUの左手(2)を攻撃。3 + 2 = 5 でDOWNします。",
  },
  {
    id: "easy-003",
    title: "4を狙え",
    difficulty: "easy",
    player: { left: 2, right: 1 },
    cpu: { left: 4, right: 0 },
    mateIn: 1,
    solution: { type: "attack", from: "right", target: "left" },
    hint: "1でも4を倒せます。",
    explanation: "右手(1)でCPUの左手(4)を攻撃。1 + 4 = 5 で勝利です。",
  },
  {
    id: "easy-004",
    title: "右手で決めろ",
    difficulty: "easy",
    player: { left: 1, right: 4 },
    cpu: { left: 0, right: 1 },
    mateIn: 1,
    solution: { type: "attack", from: "right", target: "right" },
    hint: "1に4を足すと、ちょうど5です。",
    explanation: "右手(4)でCPUの右手(1)を攻撃。CPUの最後の手がDOWNします。",
  },
  {
    id: "easy-005",
    title: "3の力",
    difficulty: "easy",
    player: { left: 2, right: 3 },
    cpu: { left: 0, right: 2 },
    mateIn: 1,
    solution: { type: "attack", from: "right", target: "right" },
    hint: "CPUの2には、3をぶつけましょう。",
    explanation: "右手(3)でCPUの右手(2)を攻撃。2 + 3 = 5 でDOWNです。",
  },
  {
    id: "normal-006",
    title: "大きい手を使う",
    difficulty: "normal",
    player: { left: 4, right: 2 },
    cpu: { left: 1, right: 0 },
    mateIn: 1,
    solution: { type: "attack", from: "left", target: "left" },
    hint: "小さいCPUの手も、4なら倒せます。",
    explanation: "左手(4)でCPUの左手(1)を攻撃。合計5でDOWN、勝利です。",
  },
  {
    id: "normal-007",
    title: "左の3",
    difficulty: "normal",
    player: { left: 3, right: 2 },
    cpu: { left: 0, right: 3 },
    mateIn: 1,
    solution: { type: "attack", from: "right", target: "right" },
    hint: "3に2を足しても5になります。",
    explanation: "右手(2)でCPUの右手(3)を攻撃。5以上になりDOWNします。",
  },
  {
    id: "normal-008",
    title: "最後の4",
    difficulty: "normal",
    player: { left: 4, right: 1 },
    cpu: { left: 4, right: 0 },
    mateIn: 1,
    solution: { type: "attack", from: "right", target: "left" },
    hint: "4には1を足すだけで十分です。",
    explanation: "右手(1)でCPUの左手(4)を攻撃。CPUの左手がDOWNして勝利です。",
  },
  {
    id: "normal-009",
    title: "右の2",
    difficulty: "normal",
    player: { left: 1, right: 2 },
    cpu: { left: 3, right: 0 },
    mateIn: 1,
    solution: { type: "attack", from: "right", target: "left" },
    hint: "3を倒すには2以上が必要です。",
    explanation: "右手(2)でCPUの左手(3)を攻撃。3 + 2 = 5 でDOWNします。",
  },
  {
    id: "normal-010",
    title: "見逃すな",
    difficulty: "normal",
    player: { left: 2, right: 4 },
    cpu: { left: 0, right: 1 },
    mateIn: 1,
    solution: { type: "attack", from: "right", target: "right" },
    hint: "最後の1は、4で倒せます。",
    explanation: "右手(4)でCPUの右手(1)を攻撃。CPUの両手がDOWNになります。",
  },
];
